<?php

use Drupal\Component\Utility\Html;

/**
 * Implements hook_theme().
 */
function mt_review_vbo_theme($existing, $type, $theme, $path) {
  return [
    'mailgun__mt_reviewer_reminder' => [
      'variables' => [
        'message' => [],
      ],
      'mail theme' => TRUE,
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function mt_review_vbo_mail($key, &$message, $params) {
  switch ($key) {
    case 'mt_reminder':
      $message['subject'] = $params['subject'];
      $message['headers']['From'] = $params['from'];
      $message['abstracts'] = $params['abstracts'];
      $message['params']['theme'] = 'mailgun__mt_reviewer_reminder';
      break;
  }
}

function mt_review_vbo_preprocess_mailgun__mt_reviewer_reminder(array &$variables)
{
  $host = \Drupal::request()->getSchemeAndHttpHost();
  $base_url = \Drupal::request()->getBaseUrl();
  $variables['base_url'] = $host . $base_url;
  $variables['abstracts'] = $variables['message']['abstracts'];
}
